### ISSUE TITLE
跑测试类的主函数扫码后错误

### ISSUE THREAD

**Issue by jason19659** [im-qq/webqq-core#18]
跑测试类的主函数扫码后错误
[][2016/06/20 10:32:52.613][INFO][ChannelLoginAction:81] {"clientid":"650379**_","ptwebqq":"be0a0c57122c15aafe4caf210c412c8b30077d890f4cd514fac71ab6b9a**_**","psessionid":"","status":"online"}
[][2016/06/20 10:32:52.739][INFO][ChannelLoginAction:92] {"errmsg":"error!!!","retcode":100001}

**Comment by im-qq** [comment]
先在webqq上面登录一下，再扫码试试？

**Comment by liaojiacan** [comment]
同样遇到这个问题。

**Comment by im-qq** [comment]
是不是拉最新的代码呢，周末的时候更新过，测试还是可以的。

**Comment by liaojiacan** [comment]
我刚刚clone下来的。

**Comment by liaojiacan** [comment]
登录成功后 302到这个页面 ，http://web2.qq.com/web2_cookie_proxy.html 

`HttpResponse [responseCode=200, responseMessage=OK, getResponseString()=<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <script type="text/javascript">
        document.domain = "qq.com";
        var domainPrefix = window.location.host;
        var cookie = {
            set : function(name, value, domain, path, hour) {
                if (hour) {
                    var today = new Date();
                    var expire = new Date();
                    expire.setTime(today.getTime() + 3600000 * hour);
                }
                window.document.cookie = name + "=" + value + "; " + (hour ? ("expires=" + expire.toGMTString() + "; ") : "") + (path ? ("path=" + path + "; ") : "path=/; ") + (domain ? ("domain=" + domain + ";") : ("domain=" + domainPrefix + ";"));
                return true;
            },
            get : function(name) {
                var r = new RegExp("(?:^|;+|\\s+)" + name + "=([^;]*)");
                var m = window.document.cookie.match(r);
                return (!m ? "" : m[1]);
            },
            remove : function(name, domain, path) {
                window.document.cookie = name + "=; expires=Mon, 26 Jul 1997 05:00:00 GMT; " + (path ? ("path=" + path + "; ") : "path=/; ") + (domain ? ("domain=" + domain + ";") : ("domain=" + domainPrefix + ";"));
            }
        };

        var getUrlParam =  function ( name ,href ,noDecode ) {
            var re = new RegExp( '(?:\\?|#|&)' + name + '=([^&]*)(?:$|&|#)',  'i' ), m = re.exec( href );
            var ret = m ? m[1] : '' ;
            return !noDecode ? decodeURIComponent( ret ) : ret;
        };

        var proxy_iframe = document.createElement("iframe");
        proxy_iframe.src = "http://web2.qq.com/web2_cookie_proxy.html";
        proxy_iframe.onload = function(){
            
            var cookieArr = proxy_iframe.contentWindow.getCookie();
            var p_skey = cookieArr[0];
            var p_uin = cookieArr[1];
            cookie.set("p_skey",p_skey);
            cookie.set("p_uin",p_uin);
            if(window.parent.mq.main.onPTLoginSuccess){
                window.parent.mq.main.onPTLoginSuccess(getUrlParam("webqq_type",location.href));
            }else{
                window.parent.location.href="http://w.qq.com/index.html?webqq_type=" + getUrlParam("webqq_type",location.href);
            }
            
        }

        document.body.appendChild(proxy_iframe);
        proxy_iframe.style.display = "none";
        
        

    </script>
</body>
</html>

]`
还需要对Cookie 进行一些设置。

**Comment by liaojiacan** [comment]
登录成功后 302到这个页面 ，http://web2.qq.com/web2_cookie_proxy.html 

`&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot;&gt;
    &lt;meta charset=&quot;UTF-8&quot;&gt;
    &lt;title&gt;登录&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;script type=&quot;text/javascript&quot;&gt;
        document.domain = &quot;qq.com&quot;;
        var domainPrefix = window.location.host;
        var cookie = {
            set : function(name, value, domain, path, hour) {
                if (hour) {
                    var today = new Date();
                    var expire = new Date();
                    expire.setTime(today.getTime() + 3600000 * hour);
                }
                window.document.cookie = name + &quot;=&quot; + value + &quot;; &quot; + (hour ? (&quot;expires=&quot; + expire.toGMTString() + &quot;; &quot;) : &quot;&quot;) + (path ? (&quot;path=&quot; + path + &quot;; &quot;) : &quot;path=/; &quot;) + (domain ? (&quot;domain=&quot; + domain + &quot;;&quot;) : (&quot;domain=&quot; + domainPrefix + &quot;;&quot;));
                return true;
            },
            get : function(name) {
                var r = new RegExp(&quot;(?:^|;+|\\s+)&quot; + name + &quot;=([^;]*)&quot;);
                var m = window.document.cookie.match(r);
                return (!m ? &quot;&quot; : m[1]);
            },
            remove : function(name, domain, path) {
                window.document.cookie = name + &quot;=; expires=Mon, 26 Jul 1997 05:00:00 GMT; &quot; + (path ? (&quot;path=&quot; + path + &quot;; &quot;) : &quot;path=/; &quot;) + (domain ? (&quot;domain=&quot; + domain + &quot;;&quot;) : (&quot;domain=&quot; + domainPrefix + &quot;;&quot;));
            }
        };

        var getUrlParam =  function ( name ,href ,noDecode ) {
            var re = new RegExp( &#x27;(?:\\?|#|&amp;)&#x27; + name + &#x27;=([^&amp;]*)(?:$|&amp;|#)&#x27;,  &#x27;i&#x27; ), m = re.exec( href );
            var ret = m ? m[1] : &#x27;&#x27; ;
            return !noDecode ? decodeURIComponent( ret ) : ret;
        };

        var proxy_iframe = document.createElement(&quot;iframe&quot;);
        proxy_iframe.src = &quot;http://web2.qq.com/web2_cookie_proxy.html&quot;;
        proxy_iframe.onload = function(){
            
            var cookieArr = proxy_iframe.contentWindow.getCookie();
            var p_skey = cookieArr[0];
            var p_uin = cookieArr[1];
            cookie.set(&quot;p_skey&quot;,p_skey);
            cookie.set(&quot;p_uin&quot;,p_uin);
            if(window.parent.mq.main.onPTLoginSuccess){
                window.parent.mq.main.onPTLoginSuccess(getUrlParam(&quot;webqq_type&quot;,location.href));
            }else{
                window.parent.location.href=&quot;http://w.qq.com/index.html?webqq_type=&quot; + getUrlParam(&quot;webqq_type&quot;,location.href);
            }
            
        }

        document.body.appendChild(proxy_iframe);
        proxy_iframe.style.display = &quot;none&quot;;
        
        

    &lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;

`
还需要对Cookie 进行一些设置。
