### ISSUE TITLE
我在beginPollMsg时候，会出现Unknown retcode: 103

### ISSUE THREAD

**Issue by xcr1234** [im-qq/webqq-core#22]
就是运行QRcodeLoginTest，扫描二维码 登录成功之后

---

[ERROR] 2016-09-16 09:56:41,027 method:iqq.im.action.PollMsgAction.onHttpStatusOK(PollMsgAction.java:211)
Unknown retcode: 103
[ERROR] 2016-09-16 09:56:41,027 method:iqq.im.action.PollMsgAction.onHttpStatusOK(PollMsgAction.java:212)

---

**Comment by yutaixi** [comment]
103这个问题解决了么？

**Comment by xcr1234** [comment]
@yutaixi 如果出现103错误，只能手动扫描登录http://smart.qq.com/，然后退出登录再重试。
建议用这个API，更加稳定：https://github.com/xcr1234/smartqq
