### ISSUE TITLE
请教问题：function getEncryption(xxxx)

### ISSUE THREAD

**Issue by hitzhangjie** [im-qq/webqq-core#5]
<pre>
       您好，请教个问题，希望你能指点一下。这几天我心血来潮，想钻研下web qq的实现，我想自己编程模
拟web qq的登录过程，做个qq机器人或者类似的程序。

       现在遇到个问题，mq_common.js里面定义的这个函数function getEncryption(xxxx)，我在chrome中对
进行调试，了解了相关的算法，现在加密的流程大体上了解了，但是不知道为什么，当我输入用户名、密码、
验证码，点击登录，对其进行调试时，我在console里面“多次输入”上述函数getEncrption(xxxxx)，发现每次
加密之后得到的md5Pwd都是不一样的！

       对此，比较困惑，查看了源代码，也没有发现其他随机变量会对加密算法产生影响啊，希望你能指点一
下。
</pre>

**Comment by im-qq** [comment]
算法我没有仔细研究过，不过一般加密传输都会加上时间戳方面的，在一定加密传输期间内有效。

**Comment by im-qq** [comment]
现在只可以使用二维登录了

**Comment by sjdy521** [comment]
getEncryption加密采用的是 md5+tea+rsa+base64组合加密方式，得到的结果并不是md5Pwd
tea和rsa在加密过程中都引入了随机参数做padding，导致每次加密后输出结果都不一样，这也是很多加密算法中都存在的比较常见的现象

**Comment by hitzhangjie** [comment]
又没有人对webqq进行过深入分析的，比如其涉及思路、文档之类的撰写。有的话，求分享，谢谢。虽然大家已经很无私了，但是文档好了，确实有利于大家学习

在 2015年10月6日 下午12:41，sjdy521 <notifications@github.com>写道：

**Comment by sjdy521** [comment]
好像也没什么思路之类的东西，也不涉及什么深入的分析，不知道你想具体学习哪方面
